version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./app:/var/www
    restart: unless-stopped
  php:
    build:
      context: .
      dockerfile: PHP.Dockerfile
    volumes:
      - ./app:/var/www/
    restart: unless-stopped
    working_dir: /var/www/
  mysql:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_USER: 'tutorial'
      MYSQL_PASSWORD: 'secret'
      MYSQL_DATABASE: 'tutorial'
    volumes:
      # use mysqldata volume to have separate local db to the production db
      # otherwise use /mysql local folder
      # - mysqldata:/var/lib/mysql
       - ./mysql:/var/lib/mysql
    ports:
        - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - mysql
volumes:
    mysqldata: {}
