version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "12540:80"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - ./app:/var/www
    restart: unless-stopped
  php:
    build:
      context: .
      dockerfile: ./docker/PHP.Dockerfile
    volumes:
      - ./app:/var/www/
    restart: unless-stopped
    working_dir: /var/www/
